name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker setup
        run: |
          sudo chmod 666 /var/run/docker.sock || true
          docker --version

      - name: Pull and rebuild Docker
        run: |
          git pull origin master
          docker stop web-pulse || true
          docker rm web-pulse || true
          docker build -t web-pulse .
          docker run -d -p 3000:3000 --name web-pulse  web-pulse

      - name: Update  environment
        run: |
          echo "Web app is running "
         